### ISSUE TITLE
phí sửa chữa manager ko hiện, staff hiện

### ISSUE THREAD

**Issue by quannthe163825** [tranngocvinh/ctms_frontend#14]
![image](https://github.com/user-attachments/assets/4f8d7dbb-3956-447d-b1ff-0d887b62f31d)
![image](https://github.com/user-attachments/assets/cf244c0e-d4d3-453b-8097-381613e4c51b)

**Comment by haihoaa** [comment]
Đã fix

**Comment by haihoaa** [comment]
Đã fix
